# Generated by Django 5.2.7 on 2025-10-23 18:03

import django.db.models.deletion
import mptt.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ad',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adattributechoice',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='produit.adattribute'),
        ),
        migrations.AddField(
            model_name='adattributevalue',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='produit.ad'),
        ),
        migrations.AddField(
            model_name='adattributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produit.adattribute'),
        ),
        migrations.AddField(
            model_name='adimage',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='produit.ad'),
        ),
        migrations.AddField(
            model_name='adreport',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='produit.ad'),
        ),
        migrations.AddField(
            model_name='adreport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adreport',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_resolved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adview',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='produit.ad'),
        ),
        migrations.AddField(
            model_name='adview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='produit.category'),
        ),
        migrations.AddField(
            model_name='adattribute',
            name='categories',
            field=models.ManyToManyField(related_name='attributes', to='produit.category'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='produit.ad'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produit.location'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', 'category', 'city'], name='produit_ad_status_d373c2_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['created_at', 'is_featured'], name='produit_ad_created_5ef20e_idx'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['price', 'category'], name='produit_ad_price_9520dd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adattributevalue',
            unique_together={('ad', 'attribute')},
        ),
        migrations.AlterUniqueTogether(
            name='adimage',
            unique_together={('ad', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='adreport',
            unique_together={('ad', 'reporter')},
        ),
        migrations.AlterUniqueTogether(
            name='adview',
            unique_together={('ad', 'ip_address', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'ad')},
        ),
    ]
