# Generated by Django 5.2.7 on 2025-10-14 20:23

import django.core.validators
import django.db.models.deletion
import produit.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre de la publicité')),
                ('link', models.URLField(verbose_name='Lien de destination')),
                ('image', models.ImageField(help_text='Taille maximale: 2Mo. Formats acceptés: jpg, jpeg, png, gif', upload_to='advertisements/', validators=[produit.models.validate_ad_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif'])], verbose_name='Affiche publicitaire')),
                ('duration_hours', models.PositiveIntegerField(default=24, help_text='Durée en heures (minimum 24h)', validators=[django.core.validators.MinValueValidator(24)])),
                ('price_per_day', models.DecimalField(decimal_places=2, default=1000, max_digits=10, verbose_name='Prix par jour (FCFA)')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
                ('impressions', models.PositiveIntegerField(default=0, verbose_name="Nombre d'affichages")),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Nombre de clics')),
            ],
            options={
                'verbose_name': 'Publicité',
                'verbose_name_plural': 'Publicités',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='ad',
            name='produit_ad_status_815451_idx',
        ),
        migrations.RenameIndex(
            model_name='ad',
            new_name='produit_ad_price_9520dd_idx',
            old_name='produit_ad_price_748a02_idx',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='location',
        ),
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.CharField(blank=True, choices=[('abidjan', 'Abidjan'), ('yamoussoukro', 'Yamoussoukro'), ('bouake', 'Bouaké'), ('daloa', 'Daloa'), ('san_pedro', 'San-Pedro'), ('korhogo', 'Korhogo'), ('man', 'Man'), ('divo', 'Divo'), ('gagnoa', 'Gagnoa'), ('abengourou', 'Abengourou'), ('anyama', 'Anyama'), ('agboville', 'Agboville'), ('grand_bassam', 'Grand-Bassam'), ('dabou', 'Dabou'), ('boundiali', 'Boundiali'), ('odienne', 'Odienné'), ('soubre', 'Soubré'), ('bingerville', 'Bingerville'), ('sassandra', 'Sassandra'), ('issia', 'Issia'), ('autre', 'Autre')], max_length=50, null=True, verbose_name='Ville'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(blank=True, choices=[('vehicules', 'Véhicules'), ('emploi_stages', "Offres d'emploi & Stages"), ('immobilier', 'Immobilier & Foncier'), ('electronique', 'Électronique & Multimédia'), ('maison_jardin', 'Maison & Jardin'), ('mode_beaute', 'Mode, Vêtements & Beauté'), ('sport_loisirs', 'Sport, Loisirs & Culture'), ('services', 'Services & Formation'), ('materiaux_pro', 'Matériaux & Équipements Pro'), ('agroalimentaire', 'Agroalimentaire & Produits locaux'), ('autre', 'Autre')], max_length=50, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
        migrations.AddIndex(
            model_name='ad',
            index=models.Index(fields=['status', 'category', 'city'], name='produit_ad_status_d373c2_idx'),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to=settings.AUTH_USER_MODEL),
        ),
    ]
