# Generated by Django 5.2.7 on 2025-11-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(blank=True, choices=[('vehicules', 'Véhicules'), ('emploi_stages', "Offres d'emploi & Stages"), ('immobilier', 'Immobilier & Foncier'), ('electronique', 'Électronique & Multimédia'), ('maison_jardin', 'Maison & Jardin'), ('mode_beaute', 'Mode, Vêtements & Beauté'), ('sport_loisirs', 'Sport, Loisirs & Culture'), ('services', 'Services & Formation'), ('materiaux_pro', 'Matériaux & Équipements Pro'), ('agroalimentaire', 'Agroalimentaire & Produits locaux'), ('Animaux_Produits animaliers', 'Animaux & Produits animaliers'), ('autre', 'Autre')], max_length=50, null=True, verbose_name='Catégorie'),
        ),
    ]
