# Generated by Django 5.2.7 on 2025-11-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0003_alter_ad_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.CharField(blank=True, choices=[('vehicules', 'Véhicules'), ('emploi_stages', "Offres d'emploi & Stages"), ('immobilier', 'Immobilier & Foncier'), ('electronique', 'Électronique & Multimédia'), ('maison_jardin', 'Maison & Jardin'), ('mode_beaute', 'Mode, Vêtements & Beauté'), ('sport_loisirs', 'Sport, Loisirs & Culture'), ('services', 'Services & Formation'), ('materiaux_pro', 'Matériaux & Équipements Pro'), ('agroalimentaire', 'Agroalimentaire & Produits locaux'), ('animaux_produits_animaliers', 'Animaux & Produits animaliers'), ('autre', 'Autre')], max_length=50, null=True, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='city',
            field=models.CharField(blank=True, choices=[('abidjan', 'Abidjan'), ('yamoussoukro', 'Yamoussoukro'), ('bouake', 'Bouaké'), ('daloa', 'Daloa'), ('san_pedro', 'San-Pedro'), ('korhogo', 'Korhogo'), ('man', 'Man'), ('divo', 'Divo'), ('seguelar', 'Seguelar'), ('gagnoa', 'Gagnoa'), ('abengourou', 'Abengourou'), ('anyama', 'Anyama'), ('agboville', 'Agboville'), ('grand_bassam', 'Grand-Bassam'), ('dabou', 'Dabou'), ('boundiali', 'Boundiali'), ('odienne', 'Odienné'), ('soubre', 'Soubré'), ('bingerville', 'Bingerville'), ('sassandra', 'Sassandra'), ('issia', 'Issia'), ('autre', 'Autre')], max_length=50, null=True, verbose_name='Ville'),
        ),
    ]
