# Generated by Django 5.2.7 on 2025-11-01 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0004_alter_ad_category_alter_ad_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='contact_phone',
        ),
    ]
