# Generated by Django 5.2.7 on 2025-11-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0005_remove_ad_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Active'), ('sold', 'Vendu'), ('expired', 'Expirée'), ('suspended', 'Suspendue'), ('rejected', 'Rejetée')], default='active', max_length=20),
        ),
    ]
