# Generated by Django 5.2.7 on 2025-10-23 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monetisation', '0001_initial'),
        ('produit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adboost',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='produit.ad'),
        ),
    ]
